global using FluentAssertions;
global using NUnit;
global using TechTalk.SpecFlow;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using DevEduEducationSystemQAA.WEB.Tests.Support;
global using DevEduEducationSystemQAA.WEB.Tests.Support.Models;
global using TechTalk.SpecFlow.Assist;
global using DevEduEducationSystemQAA.WEB.Tests.Support.XPaths;